name: Generate Release

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  generate-release:
    runs-on:  ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Archive
        run:  zip -T9 ATM7-Plus-${{github.ref}}.zip ./*

      - name: Create Release
        uses: softprops/action-gh-release.yml@v1
        with:
          generate_release_notes:   true
          draft:                    false
          prerelease:               false
          fail_on_unmatched_files:  true
          files:                    ${{github.workspace}}/*.zip
